USE [master]
GO
/****** Object:  Database [LenaDB]    Script Date: 4.10.2024 23:43:23 ******/
CREATE DATABASE [LenaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LenaDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\LenaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LenaDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS01\MSSQL\DATA\LenaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [LenaDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LenaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LenaDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LenaDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LenaDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LenaDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LenaDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [LenaDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LenaDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LenaDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LenaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LenaDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LenaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LenaDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LenaDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LenaDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LenaDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LenaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LenaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LenaDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LenaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LenaDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LenaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LenaDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LenaDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LenaDB] SET  MULTI_USER 
GO
ALTER DATABASE [LenaDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LenaDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LenaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LenaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LenaDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LenaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LenaDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [LenaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [LenaDB]
GO
/****** Object:  Table [dbo].[Forms]    Script Date: 4.10.2024 23:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Forms](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](150) NULL,
	[CreatedAt] [datetime] NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[Fields] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Forms] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 4.10.2024 23:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Forms] ON 
GO
INSERT [dbo].[Forms] ([Id], [Name], [Description], [CreatedAt], [CreatedBy], [Fields]) VALUES (6, N'Test Form', N'Deneme', CAST(N'2024-10-04T23:29:27.777' AS DateTime), 1, N'[{"Name":"Ad","Required":true,"DataType":"String"},{"Name":"Soyad","Required":true,"DataType":"String"},{"Name":"Ya\u015F","Required":false,"DataType":"Number"}]')
GO
INSERT [dbo].[Forms] ([Id], [Name], [Description], [CreatedAt], [CreatedBy], [Fields]) VALUES (7, N'Kampanya', N'indirim', CAST(N'2024-10-04T23:31:57.387' AS DateTime), 1, N'[{"Name":"\u00DCr\u00FCn ad\u0131","Required":true,"DataType":"String"},{"Name":"Adet","Required":true,"DataType":"Number"}]')
GO
SET IDENTITY_INSERT [dbo].[Forms] OFF
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([Id], [Name], [Surname], [UserName], [Password]) VALUES (1, N'Semih', N'Ünal', N'admin', N'123456')
GO
INSERT [dbo].[Users] ([Id], [Name], [Surname], [UserName], [Password]) VALUES (2, N'Kullanıcı', N'2', N'superadmin', N'123456')
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
ALTER TABLE [dbo].[Forms] ADD  CONSTRAINT [DF_Forms_CreatedAt]  DEFAULT (getdate()) FOR [CreatedAt]
GO
USE [master]
GO
ALTER DATABASE [LenaDB] SET  READ_WRITE 
GO
